export const ROUTES = {
  LOGIN:    '/login',
  HOME:     '/',
  GAME:       '/game',
  GAME_START: '/game/start',
  GAME_SAVE:  '/game/save',
  GAME_SAVE_WITH_MODE: (mode: 'continue' | 'new') => `/game/save?mode=${mode}`,
  GAME_GUIDE: '/game/guide',
  GAME_SELECT_CHARACTER: '/game/select-character',
  GAME_SET_NICKNAME: '/game/set-nickname',
  GAME_SELECT_START_METHOD: '/game/select-start-method',
  GAME_SELECT_JOB: '/game/select-job',
  GAME_NEWS: (sessionId: string | number) => `/game/${sessionId}/news`,
  GAME_NEWS_PATTERN: '/game/:sessionId/news',
  LOAN:     '/loan',
  REAL_ESTATE: '/property',
  CARD:     '/card',
  MY_PAGE:  '/mypage',
  NOT_FOUND: '*',
} as const;
