plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.11'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.asciidoctor.jvm.convert' version '4.0.5'
}

group = 'io.ssafy.p.j14c103'
version = '0.0.1-SNAPSHOT'
description = 'homerun'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    asciidoctorExt
}

repositories {
    mavenCentral()
}

ext {
    set('snippetsDir', file("build/generated-snippets"))
    set('springAiVersion', "1.1.2")
    set('ociSdkVersion', "3.81.1")
}

dependencies {
    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // Spring Security
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // AI
//    implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'
//    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    // DB
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    // Oracle OCI
    implementation "com.oracle.oci.sdk:oci-java-sdk-objectstorage:${ociSdkVersion}"
    implementation "com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey3:${ociSdkVersion}"

    // Test
    asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation platform('org.testcontainers:testcontainers-bom:1.20.4')
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers'
    testRuntimeOnly 'net.java.dev.jna:jna-platform:5.13.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

tasks.named('test') {
    outputs.dir snippetsDir
    useJUnitPlatform()
    reports {
        junitXml {
            includeSystemOutLog = false
            includeSystemErrLog = false
        }
    }
}

tasks.named('asciidoctor') {
    configurations 'asciidoctorExt'
    inputs.dir snippetsDir
    attributes 'snippets': snippetsDir
    sourceDir file('src/docs/asciidoc')
    outputDir file("$buildDir/docs/asciidoc")
    baseDirFollowsSourceFile()
    dependsOn test
}

tasks.named('bootJar') {
    dependsOn tasks.named('asciidoctor')
    from(file("$buildDir/docs/asciidoc")) {
        into 'static/docs'
    }
}
