-- Validate this SQL against local Postgres before merging any rows into homerun_dummy.sql.
-- Apply order:
--   1. schema.sql
--   2. this file

insert into financial_product_templates (
  product_type,
  institution_name,
  product_name,
  active_yn
) values
  ('SAVING_DEPOSIT', 'KB국민은행', 'KB Star 정기예금', true),
  ('SAVING_DEPOSIT', 'KB국민은행', 'KB Star 자유적금', true),
  ('SAVING_DEPOSIT', 'KB국민은행', 'KB내맘대로적금', true),
  ('SAVING_DEPOSIT', '신한은행', '쏠편한 정기예금', true),
  ('SAVING_DEPOSIT', '신한은행', '쏠편한 작심3일 적금', true),
  ('SAVING_DEPOSIT', '신한은행', '신한 안녕, 반가워 적금', true),
  ('SAVING_DEPOSIT', '하나은행', '하나의정기예금', true),
  ('SAVING_DEPOSIT', '하나은행', '급여하나 월복리 적금', true),
  ('SAVING_DEPOSIT', '하나은행', '하나 원큐 적금', true),
  ('SAVING_DEPOSIT', '우리은행', 'WON플러스 예금', true),
  ('SAVING_DEPOSIT', '우리은행', '우리 퍼스트 정기적금', true),
  ('SAVING_DEPOSIT', '우리은행', '우리 청년우대형 적금', true),
  ('SAVING_DEPOSIT', 'NH농협은행', 'NH올원e예금', true),
  ('SAVING_DEPOSIT', 'NH농협은행', 'NH직장인월복리적금', true),
  ('SAVING_DEPOSIT', 'NH농협은행', 'NH1934월복리적금', true),
  ('SAVING_DEPOSIT', '카카오뱅크', '카카오뱅크 정기예금', true),
  ('SAVING_DEPOSIT', '카카오뱅크', '카카오뱅크 자유적금', true),
  ('SAVING_DEPOSIT', '카카오뱅크', '카카오뱅크 26주적금', true),
  ('SAVING_DEPOSIT', '케이뱅크', 'codeK 정기예금', true),
  ('SAVING_DEPOSIT', '케이뱅크', 'codeK 자유적금', true),
  ('SAVING_DEPOSIT', '케이뱅크', '궁금한 적금', true),
  ('SAVING_DEPOSIT', '토스뱅크', '먼저 이자 받는 정기예금', true),
  ('SAVING_DEPOSIT', '토스뱅크', '키워봐요 적금', true),
  ('SAVING_DEPOSIT', '토스뱅크', '토스뱅크 자유적금', true),
  ('INVESTMENT', '키움증권', '국내주식 위탁종합계좌', true),
  ('INVESTMENT', '키움증권', '영웅문 글로벌 투자계좌', true),
  ('INVESTMENT', '한국투자증권', '뱅키스 주식거래계좌', true),
  ('INVESTMENT', '한국투자증권', 'CMA 종합자산계좌', true),
  ('INVESTMENT', '미래에셋증권', '다이렉트 주식거래계좌', true),
  ('INVESTMENT', '미래에셋증권', 'CMA-RP 네이버통장', true),
  ('INVESTMENT', 'NH투자증권', '나무 종합매매계좌', true),
  ('INVESTMENT', 'NH투자증권', '나무 CMA', true),
  ('INVESTMENT', '삼성증권', '종합주식거래계좌', true),
  ('INVESTMENT', '삼성증권', '연금저축 투자계좌', true),
  ('INVESTMENT', 'KB증권', 'able 주식종합계좌', true),
  ('INVESTMENT', 'KB증권', 'able CMA', true),
  ('INVESTMENT', '신한투자증권', '알파 주식거래계좌', true),
  ('INVESTMENT', '신한투자증권', 'CMA RP형 계좌', true),
  ('INVESTMENT', '대신증권', '크레온 주식종합계좌', true),
  ('INVESTMENT', '토스증권', '국내주식 거래계좌', true),
  ('LOAN', 'KB국민은행', 'KB 직장인든든 신용대출', true),
  ('LOAN', 'KB국민은행', 'KB 비상금대출', true),
  ('LOAN', 'KB국민은행', 'KB 전세금안심대출', true),
  ('LOAN', 'KB국민은행', 'KB 주택담보대출', true),
  ('LOAN', '신한은행', '쏠편한 직장인대출S', true),
  ('LOAN', '신한은행', '쏠편한 비상금대출', true),
  ('LOAN', '신한은행', '신한 전세자금대출', true),
  ('LOAN', '신한은행', '신한 주택담보대출', true),
  ('LOAN', '우리은행', 'WON플러스 직장인대출', true),
  ('LOAN', '우리은행', '우리 비상금대출', true),
  ('LOAN', '우리은행', '우리WON전세대출', true),
  ('LOAN', '우리은행', '우리WON주택대출', true),
  ('LOAN', 'NH농협은행', 'NH직장인대출V', true),
  ('LOAN', 'NH농협은행', 'NH올원 비상금대출', true),
  ('LOAN', 'NH농협은행', 'NH전세대출', true),
  ('LOAN', 'NH농협은행', 'NH주택담보대출', true),
  ('LOAN', '카카오뱅크', '카카오뱅크 비상금대출', true),
  ('LOAN', '카카오뱅크', '카카오뱅크 신용대출', true),
  ('LOAN', '케이뱅크', '케이뱅크 신용대출 플러스', true),
  ('LOAN', '토스뱅크', '토스뱅크 신용대출', true);
