{
 "title": "k6 Overview",
 "tags": [
  "homerun",
  "k6",
  "performance"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "testid",
    "label": "testid",
    "query": {
     "query": "label_values(k6_iterations_total, testid)"
    }
   },
   {
    "name": "script",
    "label": "script",
    "query": {
     "query": "label_values(k6_iterations_total{testid=~\"$testid\"}, script)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Max VUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"k6_vus.*\",testid=~\"$testid\",script=~\"$script\"})",
     "legendFormat": "vus"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_iterations_total{testid=~\"$testid\",script=~\"$script\"})",
     "legendFormat": "iterations"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"k6_.*_failed_rate\",testid=~\"$testid\",script=~\"$script\"})",
     "legendFormat": "failure-rate"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"k6_.*_duration_p95\",testid=~\"$testid\",script=~\"$script\"}) * 1000",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Latency Compare By Test ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (testid, __name__) ({__name__=~\"k6_.*_duration_p95\",testid=~\"$testid\",script=~\"$script\"}) * 1000",
     "legendFormat": "{{testid}} / {{__name__}}"
    }
   ]
  },
  {
   "title": "Iterations Compare By Test ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (testid) (k6_iterations_total{testid=~\"$testid\",script=~\"$script\"})",
     "legendFormat": "{{testid}}"
    }
   ]
  }
 ]
}