#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FRONTEND_DIR="${ROOT_DIR}/frontend"

PLAYWRIGHT_BASE_URL="${PLAYWRIGHT_BASE_URL:-http://127.0.0.1:3000}"
PLAYWRIGHT_SKIP_WEB_SERVER="${PLAYWRIGHT_SKIP_WEB_SERVER:-1}"
PLAYWRIGHT_WORKERS="${PLAYWRIGHT_WORKERS:-1}"
PLAYWRIGHT_ARTIFACTS_DIR="${PLAYWRIGHT_ARTIFACTS_DIR:-${ROOT_DIR}/.agent/private/codex/playwright-deployed-audit/artifacts/runtime-smoke}"

mkdir -p "${PLAYWRIGHT_ARTIFACTS_DIR}"

(
  cd "${FRONTEND_DIR}"
  PLAYWRIGHT_BASE_URL="${PLAYWRIGHT_BASE_URL}" \
  PLAYWRIGHT_SKIP_WEB_SERVER="${PLAYWRIGHT_SKIP_WEB_SERVER}" \
  PLAYWRIGHT_WORKERS="${PLAYWRIGHT_WORKERS}" \
  PLAYWRIGHT_ARTIFACTS_DIR="${PLAYWRIGHT_ARTIFACTS_DIR}" \
  npm run test:e2e:runtime-smoke
)
