spring:
  application:
    name: homerun
  datasource:
    url: jdbc:postgresql://localhost:5432/homerun
    username: homerun_user
    password: Local14!
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

ssafy:
  api:
    base-url: https://finopenapi.ssafy.io/ssafy/api/v1/edu
    api-key: ${SSAFY_API_KEY:your-api-key-here}
