spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_HOST_PORT:5432}/${POSTGRES_DB:homerun}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:homerun_user}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:Local14!}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

oci:
  enabled: ${OCI_ENABLED:false}
  config-path: ${OCI_CONFIG_PATH:C:/key/oci_config}
