spring:
  application:
    name: homerun
  datasource:
    url: jdbc:h2:mem:homerun
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

ssafy:
  api:
    base-url: https://finopenapi.ssafy.io/ssafy/api/v1/edu
    api-key: ${SSAFY_API_KEY:your-api-key-here}
